### PR TITLE
Fix typos in Contributing.md file

### PR DESCRIPTION
**Pull request by jinjorge**

### CODE REVIEW

**Comment by ffittschen** [comment]
@jinjorge There is another `buildwatch` -> `watchbuild` typo a few lines below ;) Just wanted to create a PR for those two before I saw this one.

**Comment by jinjorge** [comment]
I can incorporate the changes into this PR

**Comment by jinjorge** [comment]
Thanks @ffittschen for the heads up. I totally missed that one

**Comment by asfalcone** [comment]
@jinjorge Thanks for the PR! 👍

**Pull request merged**
